version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: z-commerce-app
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/z_commerce
      REDIS_URL: redis://redis:6379
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
      AWS_S3_ENDPOINT: http://localstack:4566
      AWS_S3_FORCE_PATH_STYLE: "true"
    volumes:
      - .:/app
    command: pnpm start:dev
    depends_on:
      - postgres
      - redis
      - localstack

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  localstack:
    image: localstack/localstack:3.3
    container_name: localstack
    ports:
      - "4566:4566" 
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - LOCALSTACK_HOST=localstack
    volumes:
      - localstack_data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  postgres_data:
  redis_data:
  localstack_data: